-- 202609020004_no_shk_floor_boxes_and_shelf_scan.sql
-- New flow: a box is created "на полу" (shelf_id null) and only lands on a
-- shelf via the scan-based "Перемещение коробов" flow. That flow scans a
-- shelf's own QR label (format WMSP.PLCE.WSHK.{rack_number}.{shelf_number},
-- zero-padded 2 digits each) to identify the target shelf, so racks/shelves
-- need stable numeric identifiers, not just their free-text name.
alter table public.wms_no_shk_boxes alter column shelf_id drop not null;

alter table public.wms_no_shk_racks add column rack_number integer generated by default as identity;

alter table public.wms_no_shk_shelves add column shelf_number integer;
update public.wms_no_shk_shelves s
set shelf_number = sub.rn
from (
    select id, row_number() over (partition by rack_id order by created_at) as rn
    from public.wms_no_shk_shelves
) sub
where s.id = sub.id;
alter table public.wms_no_shk_shelves alter column shelf_number set not null;

-- Shelf label template, printed once per shelf (admin panel) so it can be
-- physically scanned by the move-boxes flow. field "shelf_code" is filled
-- in by no_shk_zone.js as "WMSP.PLCE.WSHK.{rack_number}.{shelf_number}".
insert into public.print_label_templates (name, width_mm, height_mm, elements) values (
    'Полка «Без ШК»',
    50,
    50,
    '[
        {"type":"qr","field":"shelf_code","x_mm":5,"y_mm":5,"width_mm":25},
        {"type":"text","field":"shelf_code","x_mm":5,"y_mm":34,"font_size":12},
        {"type":"text","field":"shelf_name","x_mm":5,"y_mm":42,"font_size":10}
    ]'::jsonb
);
