-- 202609020002_no_shk_zone_boxes.sql
-- Boxes placed on a shelf in the "Без ШК" zone. A box has its own
-- sequential number (not tied to any product SHK -- these are exactly the
-- items without a readable barcode), matching the existing
-- "Короб без ШК {N}" label text already printed via the print bridge.
create table public.wms_no_shk_boxes (
    id uuid primary key default gen_random_uuid(),
    -- Globally sequential across the whole zone, not per-shelf/per-rack --
    -- matches "Короб без ШК {box_number}" label numbering.
    box_number integer generated by default as identity,
    shelf_id uuid not null references public.wms_no_shk_shelves(id) on delete cascade,
    created_at timestamptz not null default now()
);

create index wms_no_shk_boxes_shelf_id_idx on public.wms_no_shk_boxes (shelf_id);

alter table public.wms_no_shk_boxes enable row level security;

create policy "wms_no_shk_boxes_all" on public.wms_no_shk_boxes
    for all using (true) with check (true);
