create table if not exists public.opp_reports_cache (
  id bigint generated by default as identity primary key,
  wh_id text not null,
  cache_scope text not null,
  date_from date not null,
  date_to date not null,
  payload jsonb not null,
  source_generated_at timestamptz null,
  refreshed_at timestamptz not null default timezone('utc', now()),
  stale_after timestamptz not null default (timezone('utc', now()) + interval '30 minutes'),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint opp_reports_cache_wh_scope_period_uniq unique (wh_id, cache_scope, date_from, date_to),
  constraint opp_reports_cache_period_check check (date_from <= date_to)
);

create index if not exists opp_reports_cache_wh_scope_idx
  on public.opp_reports_cache (wh_id, cache_scope, date_from, date_to);

create index if not exists opp_reports_cache_stale_after_idx
  on public.opp_reports_cache (stale_after);

create or replace function public.set_updated_at_opp_reports_cache()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_set_updated_at_opp_reports_cache on public.opp_reports_cache;
create trigger trg_set_updated_at_opp_reports_cache
before update on public.opp_reports_cache
for each row
execute function public.set_updated_at_opp_reports_cache();

alter table public.opp_reports_cache enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'opp_reports_cache'
      and policyname = 'opp_reports_cache_select_all'
  ) then
    create policy opp_reports_cache_select_all
      on public.opp_reports_cache
      for select
      using (true);
  end if;
end $$;

grant select on public.opp_reports_cache to anon, authenticated;
