insert into public.weeek_task_routes (
  route_key,
  task_type,
  active_board_id,
  active_board_name,
  active_default_column_id,
  active_default_column_name,
  inactive_board_id,
  inactive_board_name,
  inactive_wait_column_id,
  inactive_wait_column_name,
  inactive_done_column_id,
  inactive_done_column_name,
  reopen_after_days,
  reopen_date_field_id,
  reopen_date_field_name,
  reopened_tag_name,
  deferred_verdicts,
  final_verdicts,
  not_started_verdicts
)
values (
  'incoming_flow_requests',
  'Запросы входящего потока',
  null,
  'Запросы входящего потока',
  null,
  'К разбору',
  null,
  'Запросы входящего потока',
  null,
  'К разбору',
  null,
  'Разбор завершен',
  0,
  null,
  'Дата переоткрытия',
  'Переоткрытое задание',
  array[]::text[],
  array[]::text[],
  array['Не выбран','Новая','Не начато']
)
on conflict (route_key) do update set
  task_type = excluded.task_type,
  active_board_id = excluded.active_board_id,
  active_board_name = excluded.active_board_name,
  active_default_column_id = excluded.active_default_column_id,
  active_default_column_name = excluded.active_default_column_name,
  inactive_board_id = excluded.inactive_board_id,
  inactive_board_name = excluded.inactive_board_name,
  inactive_wait_column_id = excluded.inactive_wait_column_id,
  inactive_wait_column_name = excluded.inactive_wait_column_name,
  inactive_done_column_id = excluded.inactive_done_column_id,
  inactive_done_column_name = excluded.inactive_done_column_name,
  reopen_after_days = excluded.reopen_after_days,
  reopen_date_field_id = excluded.reopen_date_field_id,
  reopen_date_field_name = excluded.reopen_date_field_name,
  reopened_tag_name = excluded.reopened_tag_name,
  deferred_verdicts = excluded.deferred_verdicts,
  final_verdicts = excluded.final_verdicts,
  not_started_verdicts = excluded.not_started_verdicts,
  updated_at = timezone('utc', now());
